spring.application.name=second

#  DATABASE
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:4306/product_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=root
spring.datasource.password=root

#  JPA / Hibernate 
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#  Keycloak 
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/ecomApp}

#  File upload 
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

#Async
spring.task.execution.pool.core-size=4
spring.task.execution.pool.max-size=16
spring.task.execution.pool.queue-capacity=100

logging.level.com.ecommerce=DEBUG
logging.level.org.springframework.security=WARN
 
server.port=8080

#swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#flyway
spring.flyway.baseline-on-migrate=true
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#gmail sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=devxpriyanshu@gmail.com
spring.mail.password=qclv dizj iynw tihq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true